"""Python side of the shared move<->action encoding (Section 9).

Loads packages/action-space/canonical-mapping.json - generated by
packages/action-space/scripts/export-canonical-mapping.ts - rather than re-deriving the 60
templates independently, so there is exactly one source of truth for the mapping instead of two
implementations that could quietly drift apart.

The combining arithmetic (action_id = origin * 60 + template_index) is simple enough to trust as
"the same by construction" as long as both sides use it identically - but "by construction" isn't
a substitute for verification, so `self_check()` below cross-checks this module's encode() against
packages/action-space/golden-fixture.json, which contains real (position, move, action_id) triples
produced by the TypeScript implementation.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

_ACTION_SPACE_DIR = Path(__file__).parent.parent / "packages" / "action-space"


@dataclass(frozen=True)
class Template:
    dr: int
    dc: int


@dataclass(frozen=True)
class ActionSpace:
    board_cols: int
    board_rows: int
    templates: tuple[Template, ...]
    action_space_size: int
    pass_action: int

    def encode(self, from_sq: int, to_sq: int, is_pass: bool) -> int | None:
        if is_pass:
            return self.pass_action
        from_row, from_col = divmod(from_sq, self.board_cols)
        to_row, to_col = divmod(to_sq, self.board_cols)
        dr, dc = to_row - from_row, to_col - from_col
        for index, t in enumerate(self.templates):
            if t.dr == dr and t.dc == dc:
                return from_sq * len(self.templates) + index
        return None

    def decode(self, action_id: int) -> tuple[int, int] | str | None:
        """Returns (from, to), 'pass', or None (out of range / off-board)."""
        if action_id == self.pass_action:
            return "pass"
        if action_id < 0 or action_id >= self.pass_action:
            return None
        from_sq, template_index = divmod(action_id, len(self.templates))
        t = self.templates[template_index]
        row, col = divmod(from_sq, self.board_cols)
        row, col = row + t.dr, col + t.dc
        if not (0 <= row < self.board_rows and 0 <= col < self.board_cols):
            return None
        return from_sq, row * self.board_cols + col


def load(mapping_path: Path = _ACTION_SPACE_DIR / "canonical-mapping.json") -> ActionSpace:
    data = json.loads(mapping_path.read_text())
    templates = tuple(Template(t["dr"], t["dc"]) for t in data["templates"])
    return ActionSpace(
        board_cols=data["boardCols"],
        board_rows=data["boardRows"],
        templates=templates,
        action_space_size=data["actionSpaceSize"],
        pass_action=data["passAction"],
    )


def self_check(
    mapping_path: Path = _ACTION_SPACE_DIR / "canonical-mapping.json",
    fixture_path: Path = _ACTION_SPACE_DIR / "golden-fixture.json",
) -> None:
    action_space = load(mapping_path)
    assert action_space.action_space_size == action_space.board_cols * action_space.board_rows * len(
        action_space.templates
    ) + 1
    assert len(action_space.templates) == 60

    fixture = json.loads(fixture_path.read_text())
    assert len(fixture) > 100, f"expected a substantial fixture, got {len(fixture)} entries"

    for entry in fixture:
        got = action_space.encode(entry["from"], entry["to"], entry["isPass"])
        assert got == entry["actionId"], (
            f"encode({entry['from']}, {entry['to']}, {entry['isPass']}) = {got}, "
            f"expected {entry['actionId']} (TypeScript golden fixture)"
        )
        if not entry["isPass"]:
            decoded = action_space.decode(entry["actionId"])
            assert decoded == (entry["from"], entry["to"]), (
                f"decode({entry['actionId']}) = {decoded}, expected ({entry['from']}, {entry['to']})"
            )

    print(f"OK: {len(fixture)}/{len(fixture)} golden fixture entries match Python encode/decode")


if __name__ == "__main__":
    self_check()
